### ISSUE TITLE
Why not an API?

### ISSUE THREAD

**Issue by blasian** [prust/wikipedia-movie-data#1]
Why not instead use the wikimedia API to create a movie API instead of using it for scraping?

**Comment by prust** [comment]
@blasian: sorry, I just now noticed this issue.

Yeah, that's a good idea. I didn't realize wikipedia (or is the API technically wikimedia?) has an API. If the API does include this data & someone wants to make the necessary adjustments to pull the data from there instead of scraping the HTML pages, I would be more than happy to accept the pull request.
